---
title: "Air BnB Amenities"
author: 'Braeden Norman'
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    includes:
      in_header: preamble.tex
    number_sections: false
    toc: FALSE
---



```{r setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(testthat)
listings <- read.csv("data/Listings.csv")
```



::: {.solbox data-latex=""}
```{r list-of-amenities}
listOfAllamenities <- vector()
amenitiesCount <- integer(length(listOfAllamenities))
for (ii in 1:length(listings$amenities)) {#length(listings$amenities)
  splitString <- strsplit(str_replace_all(listings$amenities[ii], '[^( |")[:alnum:]]', ""), '"')
  # progress tracker
  # if (ii %% 10000 == 0) print(ii)
  if (!is_empty(splitString[[1]])) {
      for (nn in 1:length(splitString[[1]])) {
      if ( (nn %% 2) == 0 && !(splitString[[1]][nn] %in% listOfAllamenities)) {
        listOfAllamenities <- c(listOfAllamenities, splitString[[1]][nn])
        amenitiesCount <- c(amenitiesCount, 0)
      }
        index <- match(splitString[[1]][nn], listOfAllamenities)
        amenitiesCount[index] <- amenitiesCount[index] + 1
    }
  }
  
}
# remove space 
amenitiesCount <- amenitiesCount[-match(" ", listOfAllamenities)]
listOfAllamenities <- listOfAllamenities[-match(" ", listOfAllamenities)]
head(listOfAllamenities)
head(amenitiesCount)
# write.csv(matrix(c(listOfAllamenities,amenitiesCount),nrow = length(listOfAllamenities), ncol = 2),"data/amenities_count.csv")
```


```{r histogram-of-amenities}
#jpeg('images/amenities_count.jpg')
barplot(amenitiesCount, ylim = c(0, 280000), main = "All amenities"
        , xlab = "Amenities Index", ylab = "Count")
lines((integer(279712) + 1)*279712, col = "red")
lines((integer(279712) + 1)*10000, col = "red")
#dev.off()

# barplot(round(log2(amenitiesCount), digits = 0), ylim =  c(0, log2(280000)) ,ylab = "Log of count")
# lines((integer(279712) + 1)*log2(279712), col = "red")
# lines((integer(279712) + 1)*log2(10000), col = "red")

noOnes <- amenitiesCount[-which( amenitiesCount < 100)]
#jpeg('images/amenities_count_reduced.jpg')
barplot(noOnes, ylim = c(0, 280000), main = "Amenities with above 100 observations"
        , xlab = "Amenities Index", ylab = "Count")
lines((integer(279712) + 1)*279712, col = "red")
lines((integer(279712) + 1)*10000, col = "red")
#dev.off()

sum(amenitiesCount > 10000)

```


```{r update-dataset}

reducedAmenities <- listOfAllamenities[which(amenitiesCount > 10000)]
reducedAmenitiesCount <- amenitiesCount[which(amenitiesCount > 10000)]

newListings <- listings


newData <- array(0, c(length(reducedAmenities),nrow(listings)))

for (ii in 1:nrow(listings)) {
  # progress tracker
  # if (ii %% 10000 == 0) print(ii)
  splitString <- strsplit(str_replace_all(listings$amenities[ii], '[^( |")[:alnum:]]', ""), '"')
  if (!is_empty(splitString[[1]])) {
    for (nn in 1:length(splitString[[1]])) {
      index <- match(splitString[[1]][nn], reducedAmenities)
      if (!is.na(index)) {
        newData[index,ii] = 1
      }
    }
  }
}

# add to new dataframe
for (ii in 1:length(reducedAmenities)) {
  newListings[,reducedAmenities[ii]] <- newData[ii,]
}


test_that("Check that count in new dataframe is same as originally calculated", {
    for (ii in 1:length(reducedAmenities)) {
      expect_equal(sum(newListings[,reducedAmenities[ii]]), reducedAmenitiesCount[ii])
    }
  })


# write.csv(newListings,"data/Listings_updated.csv")

```


```{r exploring-data}
selected <- c(1,6,10,14,22,36,54,58)
for (ii in selected) { #1:length(reducedAmenities)) {
   plt <- ggplot(newListings, aes(x = city, fill = factor(newListings[,reducedAmenities[ii]],
                         levels = c(0, 1), labels = c("False", "True")))) +
    geom_bar(position = "fill") +
    labs(y = "Percent", fill = "", x = "City", title =  paste(reducedAmenities[ii],"by City")) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
    print(plt)
}


```


:::

